In [1]:
# Using the NumPy and pandas libraries, create a small data analysis script
import numpy as np 
import pandas as pd


In [6]:
# using numpy to create a 2D Array of shape (3,3)
arr =  np.array ([[23,25,24],[1,2,3],[2,6,7]])

In [16]:

print(arr)

[[23 25 24]
 [ 1  2  3]
 [ 2  6  7]]


In [ ]:
# Performing a math operation of the whole matrix and saving it to new array
new_array = 2*arr
print(arr)


[[23 25 24]
 [ 1  2  3]
 [ 2  6  7]]


In [14]:
print(new_array)

[[46 50 48]
 [ 2  4  6]
 [ 4 12 14]]


In [19]:
#Creating a DataFrame from a dictionary

dict1 = {'product_name': ['Nothing 3A', 'CMF by Nothing 2', 'Nothing 3A Pro'], 'price': [25000, 20000,35000], 'stock_quantity':[65,50,20]}
print(dict1)

{'product_name': ['Nothing 3A', 'CMF by Nothing 2', 'Nothing 3A Pro'], 'price': [25000, 20000, 35000], 'stock_quantity': [65, 50, 20]}


In [20]:
df = pd.DataFrame(dict1)

In [21]:
df.head()

product_name  price  stock_quantity
0        Nothing 3A  25000              65
1  CMF by Nothing 2  20000              50
2    Nothing 3A Pro  35000              20

In [ ]:
# Data Filtering Operation to find and printo only the products iwth a stock_quantity greater than 50
filtered_df = df[df['stock_quantity']>50]

In [23]:
print(filtered_df)

  product_name  price  stock_quantity
0   Nothing 3A  25000              65


# End of Assignment 