# Function - Definition and Call with Params

In [13]:
def student_info(name, age = 18):
    print(name,age)

student_info("John")
student_info("Jack", 25)

John 18
Jack 25


In [1]:
from math import sqrt
sqrt(4)

2.0

# Numpy

Installation of Numpy

In [3]:
!pip install numpy

Importing Numpy

In [4]:
import numpy as np

Creating Numpy Array

In [5]:
import numpy as np 
#creating a 1D array
x=np.array([1,2,3])
#Creating a 2D array
y= np.array([[1,2],[3,4]])
#Creating a 3D array
z= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x)
print(y)
print(z)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Pandas

Installing Pandas

In [6]:
!pip install pandas

  Using cached pandas-2.3.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.3.2-cp313-cp313-win_amd64.whl (11.0 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas

Importing Pandas

In [7]:
import pandas as pd

In [8]:
#Creating a pandas series from a list 
s = pd.Series([10,20,30,40], name="My Numbers")
print(f"Pandas Series:\n{s}")
print(f"Type of Series:{type(s)}")


Pandas Series:
0    10
1    20
2    30
3    40
Name: My Numbers, dtype: int64
Type of Series:<class 'pandas.core.series.Series'>


In [12]:
#Creating a pandas DataFrame form a dictionary
data = { 'Name': ['Alice','Bob','Charlie','David'],
        'Age':[25,30,35,28],
        'City':['New York', 'London', 'Paris', 'New York'],
        'Salary':[200000,340000,450000,1200000]}
df = pd.DataFrame(data)
print(f"\nPandas DataFrame:\n{df}")


Pandas DataFrame:
      Name  Age      City   Salary
0    Alice   25  New York   200000
1      Bob   30    London   340000
2  Charlie   35     Paris   450000
3    David   28  New York  1200000


In [14]:
print(data)

{'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [25, 30, 35, 28], 'City': ['New York', 'London', 'Paris', 'New York'], 'Salary': [200000, 340000, 450000, 1200000]}
